#!/usr/bin/env python

#  this will be the main prog

#  consider this as an usage skeleton:
#  ./sk command (getenv[ironment], setenv[ironment], desc[ribe a host or a group], [sequential ]exec[ution],
#  p[arallel]_exec[ution], dist[ribute] a file, etc, ...) list_of_hosts_or_groups (-host, [+]host, [+]%group,
#  may be combined with commands,
#  probably will be prefixed differently for different group sources (foreman, casp etc)) positional_parameters (env
#  name, cmd to exec, etc)

#  Also: include command history in commands

# transited it to python2.7
# changes made: config parsing, added __init__.py to sk-modules
# commented out the super() call in ABCs for commands and parsers
# changed super() calls to match python2.7 paradigm
# you need to use python2.7 to run this shit.


import os
import swiss_knife


def main():
    cwd = os.getcwd()
    sk_dir = os.path.dirname(os.path.abspath(__file__))
    sk_path = __file__
    sk = swiss_knife.SwissKnife(cwd=cwd, sk_dir=sk_dir, sk_path=sk_path)
    sk.run()

if __name__ == "__main__":
    main()
